# HackerRank Numpy Solution

In [1]:
import numpy as np

# Q1 Arrays 
You are given a space separated list of numbers.Your task is to print a reversed NumPy array with the element type float.
Input : arr = [-10.  -8.   4.   3.   2.   1.]<br>
output : [  1.,   2.,   3.,   4.,  -8., -10.]

In [14]:
def arrays(arr):
    import numpy as np
    # complete this function
    # use numpy.array
    return np.flip(np.array(arr,float))

In [13]:
arr=[-10,  -8,   4,   3,  2,   1]
arrays(arr)

array([  1.,   2.,   3.,   4.,  -8., -10.])

# Q2 Shape and Reshape 
You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.
Input : arr = [-10.  -8.   4.   3.   2.   1. 5. 9. 6]<br>
output: <br>
([[10,  8,  4],<br>
       [ 3,  2,  1],<br>
       [ 5,  9,  6]])

In [20]:
arr=[10,8,4,3,2,1,5,9,6]
np.reshape(arr,(3,3))

array([[10,  8,  4],
       [ 3,  2,  1],
       [ 5,  9,  6]])

# Q3 Transpose and Flatten
You are given a X integer array matrix with space separated elements ( = rows and  = columns).Your task is to print the transpose and flatten results.
input:
2 2<br>
1 2<br>
3 4<br>
output:<br>
[[1 3]<br>
 [2 4]]<br>
[1 2 3 4]

In [31]:
import numpy as np
n,m=map(int,input().split(' '))
arr=np.array([input().strip().split(' ') for i in range(n)],int)
print(np.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Q4 Concatenate
You are given two integer arrays of size X and X ( &  are rows, and  is the column). Your task is to concatenate the arrays along axis .
Print the concatenated array of size X.

In [6]:
import numpy as np

n,m,p=map(int,input().split(" "))
arr1= np.array([input().strip().split(' ') for i in range(n)],int)
arr2 = np.array([ input().strip().split(' ') for i in range(m)],int)
print(np.concatenate((arr1,arr2)))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Q5 Zeros and Ones
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.
input : 3 3 3


In [6]:
import numpy as np
num=tuple(map(int,input().strip().split(" ")))
print(np.zeros(num,dtype=int))
print(np.ones(num,dtype=int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Q6 Eye and Identity
Your task is to print an array of size N*M with its main diagonal elements as 1's and 0's everywhere else.
input: 3 3 

In [16]:
n,m=map(int,input().strip().split())
print(str(np.eye(n,m)).replace('0',' 0').replace('1',' 1'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Q7 Array Mathematics 
You are given two integer  arrays, A and B of dimensions n*m.Your task is to perform the following operations:

Add (A + B)<br>
Subtract (A -B )<br>
Multiply (A *B )<br>
Integer Division (A / B)<br>
Mod ( A%B )<br>
Power ( A**B )

In [25]:
import numpy as np
n,m=map(int,input().split(' '))
arr1=np.array([input().strip().split(" ") for _ in range(n)],int)
arr2=np.array([input().strip().split(' ') for _ in range(n)],int)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1//arr2)
print(np.mod(arr1,arr2))
print(np.power(arr1,arr2))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Q8 Floor, Ceil and Rint
You are given a 1-D array, A. Your task is to print the floor,ceil  and rint of all the elements of .

In [31]:
arr1=[1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]
import numpy as np
np.set_printoptions(sign=' ') # to add space b4 the integer
#arr1=list(map(float,input().split()))
print(np.floor(arr1))
print(np.ceil(arr1))
print(np.rint(arr1))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Q9 Sum and Proud
The first line of input contains N*M space separated values of  and .The next N lines contains  M space separated integers.
input:
2 2<br>
1 2<br>
3 4

In [32]:
import numpy as np
n,m=map(int,input().split(' '))
arr1=np.array([input().strip().split(' ') for _ in range(n)],int)
add1=np.sum(arr1,axis=0)
print(np.prod(add1))

2 2
1 2
3 4
24


# Q10 Min and Max
You are given a 2-D array with dimensions n*m.Your task is to perform the min function over axis-1 and then find the max of that.

In [33]:
import numpy as np
n,m=map(int,input().split(' '))
arr=np.array([input().split(' ') for _ in range(n)],int)
print(np.max(np.min(arr,axis=1)))

4 2
2 3
5 3
7 2
1 2
3


# Q11 Mean, Var and STD
You are given a 2-D array of size n*m. Your task is to find:

The mean along axis 0<br>
The var along axis 1 <br>
The std along axis None 

In [34]:
import numpy as np
n,m=map(int,input().split(" "))
arr=np.array([input().strip().split(' ') for _ in range(n)],int)
print(np.mean(arr,axis=1))
print(np.var(arr,axis=0))
print(round(np.std(arr),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Q12 Dot and Cross
You are given two arrays A and B. Both have dimensions of N*N.
Your task is to compute their matrix product.


In [35]:
n=int(input())
arr1=np.array([input().strip().split(' ') for _ in range(n)],int)
arr2=np.array([input().strip().split(' ') for _ in range(n)],int)
print(np.dot(arr1,arr2))

2
2 5
3 4
1 6
2 7
[[12 47]
 [11 46]]


# Q13 Inner and Outer
You are given two arrays: A and B.
Your task is to compute their inner and outer product.

In [37]:
import numpy as np
arr1=np.array(input().strip().split(' '),int)
arr2=np.array(input().strip().split(' '),int)
print(np.inner(arr1,arr2))
print(np.outer(arr1,arr2))

0 1
2 3
3
[[0 0]
 [2 3]]


# Q14 Polynomial
You are given the coefficients of a polynomial P.
Your task is to find the value of P at point x.

In [1]:
import numpy as np
arr=np.array(input().strip().split(' '),float)
n=int(input())
print(np.polyval(arr,n))

1.1 2 3
0
3.0


# Q15 You are given a square matrix A with dimensions N*N. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

In [3]:
import numpy as np
n=int(input())
arr=np.array([input().strip().split(' ') for _ in range(n)],float)
print(round(np.linalg.det(arr),2))



2
1.1 1.1
1.1 1.1
0.0
